---
modes:
  - xcassets

# 资源打包模块
xcassets: 
  template:
    output: ./Sources/codes

  colors:
    - output: ./Sources/Resources/colors.xcassets
      inputs:
        - ./UI/colors

  images:
    - output: ./Sources/Resources/icons.xcassets
      report: report/images.csv
      prefix: img_
      inputs:
        - ./UI/icon
    - output: ./Sources/Resources/icons_bundle.xcassets
      prefix: img_
      bundle_name: icons_bundle
      inputs:
        - ./UI/icon
  gifs:
    - output: ./Sources/Resources/gifs.xcassets
      prefix: gif_
      inputs:
        - ./UI/gifs
